"""add category column to transactions

Revision ID: 3fec17baf330
Revises: 5bdb9200865d
Create Date: 2026-07-15 16:25:41.857040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fec17baf330'
down_revision: Union[str, None] = '5bdb9200865d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_column('transactions', 'category')
    # ### end Alembic commands ###
