"""add display_name to transactions

Revision ID: 507d011311d1
Revises: 3fec17baf330
Create Date: 2026-07-15 17:57:55.554800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507d011311d1'
down_revision: Union[str, None] = '3fec17baf330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('display_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'display_name')
    # ### end Alembic commands ###
